name: Push to dockerhub

on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Test with pytest
        run: |
          pytest

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
          
      - name: Build Docker image
        run: docker build -t shajinihubert/msegroups-quiz-service:latest -f Dockerfile .
      
      - name: Push Docker image
        run: docker push shajinihubert/msegroups-quiz-service